export const fields = [
  {
    name: "university",
    label: "University Name",
    type: "select",
    required: true,
  },
  {
    name: "program",
    label: "Program Name",
    type: "text",
    required: true,
  },
  {
    name: "duration",
    label: "Course Duration",
    type: "text",
    required: true,
  },
  {
    name: "courseContentLink",
    label: "Course Content Link",
    type: "text",
    required: true,
  },
  {
    name: "applicationFee",
    label: "Application Fee",
    type: "text",
    required: true,
  },
  {
    name: "ielts",
    label: "Ielts Requirements",
    type: "text",
    required: true,
  },
  {
    name: "pte",
    label: "PTE Requirements",
    type: "text",
    required: true,
  },
  {
    name: "toefl",
    label: "TOEFL Requirements",
    type: "text",
    required: true,
  },
  {
    name: "gre",
    label: "GRE Requirements",
    type: "text",
    required: true,
  },
  {
    name: "gmat",
    label: "GMAT Requirements",
    type: "text",
    required: true,
  },
  {
    name: "sat",
    label: "SAT Requirements",
    type: "text",
    required: true,
  },
  {
    name: "tuitionFee",
    label: "Tuition Fee",
    type: "text",
    required: true,
  },
  {
    name: "applicationLink",
    label: "Application Link",
    type: "text",
    required: true,
  },
  {
    name: "campus",
    label: "Campus Location",
    type: "text",
    required: true,
  },
  {
    name: "graduateType",
    label: "Graduation Type",
    type: "select",
    required: true,
    options: [
      { value: "ug", label: "Under Graduate" },
      { value: "pg", label: "Graduate" },
    ],
  },
  {
    name: "entryRequirement",
    label: "Entry Requirements",
    type: "text",
    required: true,
  },
  {
    name: "intake",
    label: "Select Intakes",
    type: "multiSelect",
    required: true,
    options: [
      { value: "january", label: "January" },
      { value: "february", label: "February" },
      { value: "march", label: "March" },
      { value: "april", label: "April" },
      { value: "may", label: "May" },
      { value: "June", label: "June" },
      { value: "July", label: "July" },
      { value: "august", label: "August" },
      { value: "september", label: "September" },
      { value: "october", label: "October" },
      { value: "november", label: "November" },
      { value: "December", label: "December" },
    ],
  },
];
